<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="1To4_tests.Test1To4-20151201155943" tests="4" time="0.469">
	<testcase classname="1To4_tests.Test1To4" name="test_02" time="0.136"/>
	<testcase classname="1To4_tests.Test1To4" name="test_03" time="0.120"/>
	<testcase classname="1To4_tests.Test1To4" name="test_04" time="0.111"/>
	<testcase classname="1To4_tests.Test1To4" name="test_01" time="0.102">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/home/gaems-dev/Escritorio/EGC/agora-results-tests/src/unittest/python/1To4_tests.py", line 25, in test_01
    jsonObject = json.loads(data)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
